version: "3.9"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8000:8080"
    volumes:
      - ./:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/swagger.yaml